---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: tag-system
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      namespace: tag-system
      labels:
        app: api-server
    spec:
      containers:
        - image: cr.yandex/crp2jk54p4m403rhfl0j/api:0.1
          name: api-server-instance
          args:
            - "--port"
            - "5000"
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-secret
            - secretRef:
                name: jwt-secret
            - configMapRef:
                name: python-server-config
