---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: tag-system
  labels:
    app: api-server
spec:
  ports:
    - name: api-port
      port: 5000
      targetPort: 5000
  selector:
    app: api-server
