---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: tag-system
  labels:
    app: web-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      namespace: tag-system
      labels:
        app: web-ui
    spec:
      containers:
        - image: cr.yandex/crp2jk54p4m403rhfl0j/web:0.4
          name: web-ui-instance
          ports:
            - containerPort: 3000
