---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: tag-system
  labels:
    app: web-ui
spec:
  ports:
    - name: web-ui
      port: 3000
      targetPort: 3000
  selector:
    app: web-ui
