---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-server
  namespace: tag-system
  labels:
    app: auth-api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api-server
  template:
    metadata:
      namespace: tag-system
      labels:
        app: auth-api-server
    spec:
      containers:
        - image: cr.yandex/crp2jk54p4m403rhfl0j/auth_api:0.2
          name: auth-api-instance
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-secret
            - secretRef:
                name: jwt-secret
            - configMapRef:
                name: python-server-config
