---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: tag-system
  labels:
    app: worker
spec:
  ports:
    - name: worker-port
      port: 5000
      targetPort: 5000
  selector:
    app: worker
